# See https://pre-commit.com for more information

default_language_version:
  python: python3.9

ci:
  autofix_prs: false

default_stages: [commit, push]
exclude: (^debug/|^docs/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/PyCQA/isort
    rev: v5.11.3
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
